# Generated by Django 4.2.2 on 2023-06-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalExpense', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bikename',
            new_name='name',
        ),
    ]
