# Generated by Django 4.2.2 on 2023-06-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalExpense', '0002_rename_bikename_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productname',
            new_name='name',
        ),
    ]
