# Generated by Django 4.2.2 on 2023-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalExpense', '0003_rename_productname_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Emergency', 'Emergency'), ('Plan', 'Plan')], max_length=200, null=True),
        ),
    ]
