# Generated by Django 4.2.2 on 2023-06-28 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('generalExpense', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Vehicle',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='vehicle',
        ),
    ]
